[package]
name = "gjio"
version = "0.0.1"
authors = ["David Renshaw <david@sandstorm.io>"]
license = "MIT"
repository = "https://github.com/dwrensha/gj"

readme = "README.md"

[dependencies.gj]
git = "https://github.com/dwrensha/gj.git"

[dependencies]
nix = "0.5"
time = "0.1"